### ISSUE TITLE
anki2sm fails to convert mp3 files with parantheses

### ISSUE THREAD

**Issue by plug-unplug** [AM429/anki2sm#9]
The bug can be seen with these files:
[Default.zip](https://github.com/AM429/anki2sm/files/5642894/Default.zip)
when I attempt to convert them with anki2sm, they convert but without the audio. In one of the cards, audio converts too but only because I manually edited the parentheses out of the audio file and the audio field in Anki.

Not sure what's causing this, if it could be fixed in code would be ideal since doing so by hand would be time consuming.

**Comment by ghost** [comment]
Fixed, hopefully should work now

**Comment by rajlego** [comment]
images are still failing to convert, maybe apply same fix for mp3 to images as well

I know I did have those working somehow before but not sure what was different

**Comment by ghost** [comment]
Hmm I am not sure I am able to replicate the issue, both modes (embedded and as an image component) appear to be working fine, with regards to the attached apkg.
Separate image component: 
![image](https://user-images.githubusercontent.com/58094765/102895589-9fea7980-446d-11eb-855d-74ae33125eee.png)
Embedded image: 
![image](https://user-images.githubusercontent.com/58094765/102895783-02437a00-446e-11eb-8b80-ecba4c443d65.png)

**Comment by rajlego** [comment]
I'm using not embedded mode (so it puts it normally into components such
that styling from sm effects it), maybe that's it?

~Raj
